### ISSUE TITLE
Won't run for some reason

### ISSUE THREAD

**Issue by eoghan2t9** [hyp3rd/telegram-discord-bridge#31]
Hi

I have set up the python venv and edited the config.yml for my needs however when i go to run the app it fails to start and this is all i get from the logs so i hope it helps

2023-05-17 03:18:53,753 - Sports Lister - WARNING - Discord Client's internal cache is not ready
2023-05-17 03:18:53,915 - Sports Lister - ERROR - No input channels found, exiting

I am unsure why im getting this error as the config definitely has the channel ID i wish to forward too. Any ideas would get helpful before I pull the rest of my hair out trying to figure it out lol

**Comment by hyp3rd** [comment]
Hey there, something is off in the telegram_forwarders section of your config file.

Would you be able to share that snippet of your configuration?

**Comment by hyp3rd** [comment]
To give you more context, when the bridge tries registering your forwarders, it doesn't find one or more Telegram channels you've put in the config file:

```python
            if tg_channel_id in {dialog.name, dialog.entity.id}:  # type: ignore
                input_channels_entities.append(
                    InputChannel(dialog.entity.id, dialog.entity.access_hash))  # type: ignore
                discord_channel_mappings[forwarder_name] = discord_channel_config
                logger.info("Registered TG channel '%s' with ID %s with Discord channel config %s",
                            dialog.name, dialog.entity.id, discord_channel_config)  # type: ignore

    if not input_channels_entities:
        logger.error("No input channels found, exiting")
        sys.exit(1)
```

The config file in the forwarders section should look like the following:

```yaml
  - forwarder_name: "some name"
    tg_channel_id: 123456789
    discord_channel_id: 987654321012345678
    mention_everyone: False
    strip_off_links: False
    forward_everything: True
    forward_hashtags:
      - name: "#ta"

  - forwarder_name: "some other name"
    tg_channel_id: 987654321
    discord_channel_id: 876543210123456789
    strip_off_links: False
    mention_everyone: False
    forward_everything: True
    mention_override:
      - tag: "#important"
        roles: ["everyone"]
    excluded_hashtags:
      - name: "#sponsored"
      - name: "#sponsor"
      - name: "#news"
```

**Comment by hyp3rd** [comment]
Hello, the error you receive is expected because your config is wrong: 
You're not providing the Telegram source `tg_channel_id` and the Discord destination `discord_channel_id`

 ```yaml
 # The channels map to discord channels.
 telegram_forwarders:
   - forwarder_name: "Sports Listing"
     tg_channel_id: # <<<< here you need to specify the ID of the Telegram channel you want to use as source
     discord_channel_id:  # <<< here you need to specify the ID of the Discord channel you want as destination
     strip_off_links: False # whether to strip off links from the message
     mention_everyone: false
     forward_everything: true # whether forwarding everything regardless the hashtag
   ```
